"""Add NIRF phase 3 models

Revision ID: 981b165a45c3
Revises: aa6a961ea298
Create Date: 2026-05-24 22:00:07.834548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '981b165a45c3'
down_revision: Union[str, Sequence[str], None] = 'aa6a961ea298'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('executive_development_programs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('participants', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('annual_earnings', sa.Float(), server_default=sa.text('0.0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_executive_development_programs_college_id'), 'executive_development_programs', ['college_id'], unique=False)
    op.create_index(op.f('ix_executive_development_programs_id'), 'executive_development_programs', ['id'], unique=False)
    op.create_index(op.f('ix_executive_development_programs_is_deleted'), 'executive_development_programs', ['is_deleted'], unique=False)
    op.create_table('research_organizations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('org_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_organizations_college_id'), 'research_organizations', ['college_id'], unique=False)
    op.create_index(op.f('ix_research_organizations_id'), 'research_organizations', ['id'], unique=False)
    op.create_index(op.f('ix_research_organizations_is_deleted'), 'research_organizations', ['is_deleted'], unique=False)
    op.create_table('consultancy_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('faculty_id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('amount_received', sa.Float(), server_default=sa.text('0.0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['faculty_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['research_organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultancy_records_college_id'), 'consultancy_records', ['college_id'], unique=False)
    op.create_index(op.f('ix_consultancy_records_id'), 'consultancy_records', ['id'], unique=False)
    op.create_index(op.f('ix_consultancy_records_is_deleted'), 'consultancy_records', ['is_deleted'], unique=False)
    op.create_table('patent_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('faculty_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('calendar_year', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['faculty_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patent_records_college_id'), 'patent_records', ['college_id'], unique=False)
    op.create_index(op.f('ix_patent_records_id'), 'patent_records', ['id'], unique=False)
    op.create_index(op.f('ix_patent_records_is_deleted'), 'patent_records', ['is_deleted'], unique=False)
    op.create_table('sponsored_research_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('faculty_id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('amount_received', sa.Float(), server_default=sa.text('0.0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['faculty_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['research_organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sponsored_research_records_college_id'), 'sponsored_research_records', ['college_id'], unique=False)
    op.create_index(op.f('ix_sponsored_research_records_id'), 'sponsored_research_records', ['id'], unique=False)
    op.create_index(op.f('ix_sponsored_research_records_is_deleted'), 'sponsored_research_records', ['is_deleted'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f('ix_sponsored_research_records_is_deleted'), table_name='sponsored_research_records')
    op.drop_index(op.f('ix_sponsored_research_records_id'), table_name='sponsored_research_records')
    op.drop_index(op.f('ix_sponsored_research_records_college_id'), table_name='sponsored_research_records')
    op.drop_table('sponsored_research_records')
    op.drop_index(op.f('ix_patent_records_is_deleted'), table_name='patent_records')
    op.drop_index(op.f('ix_patent_records_id'), table_name='patent_records')
    op.drop_index(op.f('ix_patent_records_college_id'), table_name='patent_records')
    op.drop_table('patent_records')
    op.drop_index(op.f('ix_consultancy_records_is_deleted'), table_name='consultancy_records')
    op.drop_index(op.f('ix_consultancy_records_id'), table_name='consultancy_records')
    op.drop_index(op.f('ix_consultancy_records_college_id'), table_name='consultancy_records')
    op.drop_table('consultancy_records')
    op.drop_index(op.f('ix_research_organizations_is_deleted'), table_name='research_organizations')
    op.drop_index(op.f('ix_research_organizations_id'), table_name='research_organizations')
    op.drop_index(op.f('ix_research_organizations_college_id'), table_name='research_organizations')
    op.drop_table('research_organizations')
    op.drop_index(op.f('ix_executive_development_programs_is_deleted'), table_name='executive_development_programs')
    op.drop_index(op.f('ix_executive_development_programs_id'), table_name='executive_development_programs')
    op.drop_index(op.f('ix_executive_development_programs_college_id'), table_name='executive_development_programs')
    op.drop_table('executive_development_programs')
    # ### end Alembic commands ###
