"""Add course materials

Revision ID: e64b3fef3e85
Revises: d66fcfa345f2
Create Date: 2026-06-01 22:44:30.450879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e64b3fef3e85'
down_revision: Union[str, Sequence[str], None] = 'd66fcfa345f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_materials',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('college_id', sa.String(), nullable=False),
    sa.Column('course_id', sa.String(), nullable=False),
    sa.Column('faculty_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('material_type', sa.String(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=True),
    sa.Column('web_link', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['faculty_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_course_material_course', 'course_materials', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_materials_id'), 'course_materials', ['id'], unique=False)
    op.create_index(op.f('ix_course_materials_is_deleted'), 'course_materials', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_course_materials_is_deleted'), 'course_materials', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    op.drop_index(op.f('ix_course_materials_is_deleted'), table_name='course_materials')
    op.drop_index(op.f('ix_course_materials_id'), table_name='course_materials')
    op.drop_index('ix_course_material_course', table_name='course_materials')
    op.drop_table('course_materials')
    # ### end Alembic commands ###
