import React from 'react';
import { Blueprint, Calculator, CheckCircle, Clock, Compass, Cube, Drop, Gauge, HardHat, Path, Stack, Tree, Wall } from '@phosphor-icons/react';
import type { CivilStudioTool } from './civilTypes';

const toolMeta: Record<CivilStudioTool, { title: string; subtitle: string; accent: string; icon: React.ReactNode }> = {
  structural: {
    title: 'Structural Analysis Studio',
    subtitle: 'Beam reactions, SFD/BMD, deflection and serviceability checks',
    accent: 'rose',
    icon: <Blueprint size={24} weight="duotone" />,
  },
  geotech: {
    title: 'Geotechnical Bearing Studio',
    subtitle: 'Terzaghi bearing capacity with safety and soil-state insight',
    accent: 'amber',
    icon: <Stack size={24} weight="duotone" />,
  },
  hydraulics: {
    title: 'Hydraulics Flow Studio',
    subtitle: 'Pipe head loss, pump power and open-channel Manning flow',
    accent: 'sky',
    icon: <Drop size={24} weight="duotone" />,
  },
  survey: {
    title: 'Survey Traverse Studio',
    subtitle: 'Bowditch correction, coordinate plotting, area and precision',
    accent: 'emerald',
    icon: <Compass size={24} weight="duotone" />,
  },
  cad: {
    title: 'CAD/BIM Quantity Sketcher',
    subtitle: 'Grid planning, bay quantities and early structural takeoff',
    accent: 'violet',
    icon: <Cube size={24} weight="duotone" />,
  },
  transport: {
    title: 'Road Geometry Studio',
    subtitle: 'Sight distance, superelevation, curve and capacity checks',
    accent: 'indigo',
    icon: <Path size={24} weight="duotone" />,
  },
  environment: {
    title: 'Environmental Systems Studio',
    subtitle: 'Water demand, treatment tank sizing and BOD process checks',
    accent: 'teal',
    icon: <Tree size={24} weight="duotone" />,
  },
  concrete: {
    title: 'RCC Beam Design Studio',
    subtitle: 'Flexural steel, ductility, spacing and utilization checks',
    accent: 'rose',
    icon: <Wall size={24} weight="duotone" />,
  },
  estimation: {
    title: 'Quantity & BBS Studio',
    subtitle: 'Concrete, cement, aggregates, reinforcement and cost takeoff',
    accent: 'amber',
    icon: <Calculator size={24} weight="duotone" />,
  },
  planning: {
    title: 'Construction Planning Studio',
    subtitle: 'CPM, floats, critical path and Gantt visualization',
    accent: 'violet',
    icon: <Clock size={24} weight="duotone" />,
  },
  steel: {
    title: 'Steel Structure Design Studio',
    subtitle: 'Tension, compression, slenderness and utilization checks',
    accent: 'sky',
    icon: <Blueprint size={24} weight="duotone" />,
  },
  retaining: {
    title: 'Retaining Wall & Slope Studio',
    subtitle: 'Earth pressure, sliding, overturning and bearing checks',
    accent: 'amber',
    icon: <Stack size={24} weight="duotone" />,
  },
  waterNetwork: {
    title: 'Water Supply Network Studio',
    subtitle: 'Loop demand, head loss, velocity and Hardy-Cross style balance',
    accent: 'teal',
    icon: <Drop size={24} weight="duotone" />,
  },
  openChannel: {
    title: 'Open Channel Design Studio',
    subtitle: 'Trapezoidal canal, Froude number, discharge and lining checks',
    accent: 'sky',
    icon: <Drop size={24} weight="duotone" />,
  },
  pavement: {
    title: 'Pavement Design Studio',
    subtitle: 'CBR, traffic, flexible layers and rigid slab thickness',
    accent: 'indigo',
    icon: <Path size={24} weight="duotone" />,
  },
  leveling: {
    title: 'Survey Leveling Studio',
    subtitle: 'HI method, rise/fall checks, contour interpolation and closing error',
    accent: 'emerald',
    icon: <Compass size={24} weight="duotone" />,
  },
  mixDesign: {
    title: 'Concrete Mix Design Studio',
    subtitle: 'Target strength, w/c ratio, moisture correction and material yield',
    accent: 'rose',
    icon: <Wall size={24} weight="duotone" />,
  },
  costEstimator: {
    title: 'Construction Cost Estimator',
    subtitle: 'Excavation, PCC, RCC, masonry, finishing and live rate sensitivity',
    accent: 'amber',
    icon: <Calculator size={24} weight="duotone" />,
  },
  frame: {
    title: 'Frame Analysis Studio',
    subtitle: 'Portal frame loads, approximate drift, reactions and moment demand',
    accent: 'rose',
    icon: <Blueprint size={24} weight="duotone" />,
  },
  truss: {
    title: 'Truss Analysis Studio',
    subtitle: 'Span, panel geometry, nodal load and member-force visualization',
    accent: 'sky',
    icon: <Blueprint size={24} weight="duotone" />,
  },
  soilLab: {
    title: 'Soil Classification & Compaction Studio',
    subtitle: 'Sieve, Atterberg, USCS/IS interpretation and Proctor curve insight',
    accent: 'amber',
    icon: <Stack size={24} weight="duotone" />,
  },
  earthwork: {
    title: 'GIS / Contour / Earthwork Studio',
    subtitle: 'Grid levels, contour slope, cut-fill balancing and haul estimate',
    accent: 'emerald',
    icon: <Compass size={24} weight="duotone" />,
  },
  bridge: {
    title: 'Bridge Basics Studio',
    subtitle: 'Deck span, IRC-style live load, girder reactions and distribution',
    accent: 'indigo',
    icon: <Path size={24} weight="duotone" />,
  },
  columnFooting: {
    title: 'Column & Footing Design Studio',
    subtitle: 'Axial load, eccentricity, footing pressure, shear and sizing checks',
    accent: 'rose',
    icon: <Wall size={24} weight="duotone" />,
  },
  masonry: {
    title: 'Masonry Design Studio',
    subtitle: 'Wall load, slenderness, opening effect and lintel load path checks',
    accent: 'amber',
    icon: <Wall size={24} weight="duotone" />,
  },
  rebar: {
    title: 'Rebar Detailing Studio',
    subtitle: 'Anchorage, lap, hook, spacing and bar bending schedule quantities',
    accent: 'rose',
    icon: <Wall size={24} weight="duotone" />,
  },
  formwork: {
    title: 'Formwork & Scaffolding Studio',
    subtitle: 'Panel quantity, prop spacing, pour pressure and reuse-cycle costing',
    accent: 'violet',
    icon: <Cube size={24} weight="duotone" />,
  },
  pile: {
    title: 'Pile Group Studio',
    subtitle: 'Pile capacity, group efficiency, settlement indicator and layout',
    accent: 'amber',
    icon: <Stack size={24} weight="duotone" />,
  },
  seismic: {
    title: 'Seismic Design Studio',
    subtitle: 'Base shear, response factor, storey drift and soft-storey signal',
    accent: 'rose',
    icon: <Gauge size={24} weight="duotone" />,
  },
  wind: {
    title: 'Wind Load Studio',
    subtitle: 'IS 875-style wind pressure, height factor and cladding load map',
    accent: 'sky',
    icon: <Gauge size={24} weight="duotone" />,
  },
  services: {
    title: 'Building Services Civil Studio',
    subtitle: 'Rainwater pipes, septic tank, soak pit and fire tank sizing',
    accent: 'teal',
    icon: <Drop size={24} weight="duotone" />,
  },
  equipment: {
    title: 'Construction Equipment Productivity Studio',
    subtitle: 'Excavator, dumper, pump and batching cycle productivity checks',
    accent: 'violet',
    icon: <Clock size={24} weight="duotone" />,
  },
  qcLab: {
    title: 'Quality Control Lab Studio',
    subtitle: 'Slump, cube, sieve, density and bitumen test interpretation',
    accent: 'emerald',
    icon: <CheckCircle size={24} weight="duotone" />,
  },
  tender: {
    title: 'Tender & BOQ Comparison Studio',
    subtitle: 'Rate analysis, L1/L2/L3 comparison and item-wise variance risk',
    accent: 'amber',
    icon: <Calculator size={24} weight="duotone" />,
  },
  siteLayout: {
    title: 'Site Layout Planning Studio',
    subtitle: 'Crane reach, storage zones, access paths and safety buffer planning',
    accent: 'indigo',
    icon: <Cube size={24} weight="duotone" />,
  },
  bimRevit: {
    title: 'BIM / Revit Concept Studio',
    subtitle: 'Model levels, grid planning, quantities and coordination issue checks',
    accent: 'violet',
    icon: <Cube size={24} weight="duotone" />,
  },
  bbs: {
    title: 'Bar Bending Schedule Studio',
    subtitle: 'Cut length, bends, laps, hooks, weight and wastage control',
    accent: 'rose',
    icon: <Wall size={24} weight="duotone" />,
  },
  rateAnalysis: {
    title: 'Rate Analysis Studio',
    subtitle: 'Material, labour, equipment, overhead and contractor margin breakdown',
    accent: 'amber',
    icon: <Calculator size={24} weight="duotone" />,
  },
  isCodeChecker: {
    title: 'IS Code Design Checker',
    subtitle: 'Quick compliance checks for RCC, steel, wind, seismic and serviceability',
    accent: 'emerald',
    icon: <CheckCircle size={24} weight="duotone" />,
  },
  safetyInspection: {
    title: 'Construction Safety Inspection Studio',
    subtitle: 'Scaffold, excavation, lifting, PPE and site-risk inspection scoring',
    accent: 'rose',
    icon: <WarningCircle size={24} weight="duotone" />,
  },
  draftingPractice: {
    title: 'AutoCAD Drafting Practice Board',
    subtitle: 'Scale, linework, offsets, dimensions and drawing accuracy checks',
    accent: 'sky',
    icon: <Blueprint size={24} weight="duotone" />,
  },
  staadFrame: {
    title: 'STAAD-like Frame Modeler',
    subtitle: 'Nodes, members, supports, loads and utilization for placement workflows',
    accent: 'indigo',
    icon: <Blueprint size={24} weight="duotone" />,
  },
  projectControl: {
    title: 'Project Planning Cost-Control Studio',
    subtitle: 'Earned value, planned vs actual progress, SPI/CPI and delay impact',
    accent: 'violet',
    icon: <Clock size={24} weight="duotone" />,
  },
  claimsDelay: {
    title: 'Contract Claims & Delay Analysis Studio',
    subtitle: 'EOT, liquidated damages, delay ownership and claim value checks',
    accent: 'amber',
    icon: <Calculator size={24} weight="duotone" />,
  },
  qaDocs: {
    title: 'Construction QA Document Studio',
    subtitle: 'ITP, pour card, cube register, inspection request and NCR readiness',
    accent: 'emerald',
    icon: <CheckCircle size={24} weight="duotone" />,
  },
  setout: {
    title: 'Site Survey Layout Setout Studio',
    subtitle: 'Coordinate setout, offsets, gridline marking and closure error checks',
    accent: 'emerald',
    icon: <Compass size={24} weight="duotone" />,
  },
  roadCrossSection: {
    title: 'Road Estimation & Cross-Section Studio',
    subtitle: 'Chainage-wise cut/fill, camber, shoulder and pavement layer quantities',
    accent: 'indigo',
    icon: <Path size={24} weight="duotone" />,
  },
  stormwater: {
    title: 'Drainage & Stormwater Network Studio',
    subtitle: 'Catchment runoff, pipe sizing, slope and manhole spacing checks',
    accent: 'teal',
    icon: <Drop size={24} weight="duotone" />,
  },
  drawingTakeoff: {
    title: 'Quantity Takeoff From Drawing Studio',
    subtitle: 'Drawing-scale walls, slab, openings and area/volume extraction',
    accent: 'sky',
    icon: <Blueprint size={24} weight="duotone" />,
  },
};

export { toolMeta };
